version: "3.8"
services:
  db:
    image: "postgres:16.1"
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: "marvin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "hibernate_performance"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data:
